### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by YourShinko** [yor42/Solar-Apocalypse-Reforged#3]
I'm used to downloading a mod and it already being ready to just drop into the mod file, this one doesn't work that way, any tip on how to get it to work in my mod pack?

**Comment by yor42** [comment]
this one should work that way
maybe check your config file?

**Comment by YourShinko** [comment]
Sorry! I figured it out, I'm new to github and downloaded it wrong! btw Thank you so much for making this version of solar apocalypse :D! I can use it in my SMP I'm opening :)

**Comment by yor42** [comment]
you're welcome
