### ISSUE TITLE
1.18 Version?

### ISSUE THREAD

**Issue by NazarDoeH** [yor42/Solar-Apocalypse-Reforged#4]
Can you make 1.18 version please...

**Comment by yor42** [comment]
Currently major problem is i have 0 experience on modding 1.18.1 and i have another mod currently working on.
but since this mod is fairly small and i have to move on to 1.18 eventually, I'll look into it.
but PLEASE do note that it won't be my top priority.

**Comment by NazarDoeH** [comment]
Ok, thanks.

**Comment by MagentaLizard** [comment]
Update potentially soon?

**Comment by yor42** [comment]
Well I'm trying, but I'm having issue with gradle recently. I can't work on 1.18 at all because of this...
will start working on it when i get around this.

**Comment by yor42** [comment]
Great news for you guys; check release page.

**Comment by FrozenDragon0** [comment]
> Great news for you guys; check release page.

Will 1.19.2 follow behind shortly after aswell? Just curious.

**Comment by yor42** [comment]
Sadly, No. I do not have plan for 1.19+ in foreseeable future.

**Comment by yor42** [comment]
BUT this mod is very simple in code. so if you have basic understanding in java and minecraft along with mixin, you will have no problem porting it yourself.

**Comment by darthvader45** [comment]
Ah, I'll keep that in mind.

**Comment by FrozenDragon0** [comment]
> Sadly, No. I do not have plan for 1.19+ in foreseeable future.

Well guess I'll be waiting awhile then or unless someone else wants to do it, attempted to try update it myself but got absolutely nowhere :/ Tutorials on YT didn't really help.
