### ISSUE TITLE
Installation (github)

### ISSUE THREAD

**Issue by imnewo** [yor42/Solar-Apocalypse-Reforged#5]

**Comment by yor42** [comment]
on main screen go to release page.
download the jar, and put jar on mods folder in your instance folder.

**Comment by Bruce6131** [comment]
There is no jar file for me

**Comment by imnewo** [comment]
@Bruce6131 
For 1.18.2 : [Download](https://github.com/yor42/Solar-Apocalypse-Reforged/releases/download/V1.11/solarapocalypse-1.18.2-1.11.jar)
For 1.16.5 : [Download](https://github.com/yor42/Solar-Apocalypse-Reforged/releases/download/V1.11/solarapocalypse-1.16.5-1.11.jar)
