### ISSUE TITLE
1.19.2 Solar Apocalypse?

### ISSUE THREAD

**Issue by darthvader45** [yor42/Solar-Apocalypse-Reforged#8]
Got curious when I saw it was on 1.18.2, and wondered if it would go further.  I remember Ivorius' original version of the mod and the showcase of it.  Imagine that kind of horror in the newest versions.

**Comment by yor42** [comment]
https://github.com/yor42/Solar-Apocalypse-Reforged/issues/4#issuecomment-1296089121

please refer to this comments.
