### ISSUE TITLE
Chances of a downgrade to 1.12.2?

### ISSUE THREAD

**Issue by Neko-LoverDisc** [yor42/Solar-Apocalypse-Reforged#9]
I know its probably a long shot, but I've been wanting this mod for years on 1.7.10 and 1.12.2, and I was wondering if you'd be willing to backport it to 1.12.2? I'd very much appreciate this

**Comment by yor42** [comment]
Actually, backport to 1.12.2 was something that was actually on the horizon, and there was some of work done.
but problem is that I am returning to college very soon. (next week) therefore I don't have time to work on project like this anymore.

**Comment by Neko-LoverDisc** [comment]
RIP that sucks, hopefully someone else can do this then
